    <p><span class="biblat"><acronym title="{_('Bibliografía Latinoamericana')}">Biblat</acronym></span>: {_('fuente bibliométrica para conocer la productividad científica de América Latina y el Caribe')}</p>
		          
    <p><span class="biblat"><acronym title="{_('Bibliografía Latinoamericana')}">Biblat</acronym></span> {$clase=_('Citas Latinoamericanas en Ciencias Sociales y Humanidades') $periodica=_('Índice de Revistas Latinoamericanas en Ciencias') $biblat=_('Bibliografía Latinoamericana') _sprintf('es un portal especializado en la generación de frecuencias e indicadores bibliométricos de las bases de datos %s (Citas Latinoamericanas en Ciencias Sociales y Humanidades) y %s (Índice de Revistas Latinoamericanas en Ciencias), el cual ha sido concebido como una fuente de información que permite conocer las características de la producción científica de América Latina y el Caribe publicada en revistas académicas de la región. Para tal fin, %s conjunta y sistematiza la información contenida en %s y %s, las bases de datos bibliográficas con el conjunto más representativo e incluyente de revistas académicas publicadas en América Latina y el Caribe (más de 4 mil revistas y más de 1,000,000 registros bibliográficos entre ambas bases). Por otra parte, dichas bases de datos cuentan con una','<a href="https://clase.dgb.unam.mx" target="_blank"><acronym title="$clase">CLASE</acronym></a>','<a href="https://periodica.dgb.unam.mx" target="_blank"><acronym title="$periodica">PERIÓDICA</acronym></a>','<span class="biblat"><acronym title="$biblat">Biblat</acronym></span>','<a href="https://clase.dgb.unam.mx" target="_blank"><acronym title="$clase">CLASE</acronym></a>','<a href="https://periodica.dgb.unam.mx" target="_blank"><acronym title="$periodica">PERIÓDICA</acronym></a>')} <a href="{site_url("clase-y-periodica")}" target="_blank">{_('cobertura multidisciplinaria en todas las áreas del conocimiento.')}</a></p>

    <p>{_sprintf('La muestra de las frecuencias e indicadores bibliométricos aportados por %s está conformada por las publicaciones de América Latina y el Caribe y sus correspondientes registros bibliográficos indizados en %s y %s. Las revistas y registros bibliográficos indizados por base de datos son:','<span class="biblat"><acronym title="$biblat">Biblat</acronym></span>','<a href="https://clase.dgb.unam.mx" target="_blank"><acronym title="$clase">CLASE</acronym></a>','<a href="https://periodica.dgb.unam.mx" target="_blank"><acronym title="$periodica">PERIÓDICA</acronym></a>')}</p>

    <p>La selección de las publicaciones seriadas y periódicas que ingresan a las dos bases de datos es realizada por un comité de evaluación y selección conforme los lineamientos contenidos en el <a href="{base_url('archivos/pdf/Reglamento_Comite_firmado_may-2022.pdf')}" target="_blank">"Reglamento del Comité de Evaluación y Selección de Publicaciones Seriadas para las bases de datos CLASE y PERIÓDICA, portal BIBLAT y catálogo SeriUNAM"</a>. Para consultar los criterios editoriales que se utilizan en la selección de las revistas véase <a href="https://biblat.unam.mx/es/postular-revista/criterios-de-seleccion" target="_blank"><acronym title="Criterios de selección">criterios de selección.</acronym></a></p>

    <p>{_sprintf('Tipo de publicación y de documento indizados: en %s y %s se indizan diversos tipos de revistas, las cuales pueden ser clasificadas como revistas de investigación científica, de carácter técnico-profesional y de divulgación científica y cultural. Desde 1997, el Comité de Evaluación y Selección prioriza la inclusión de revistas de investigación científica y humanística, dirigidas a especialistas, así como revistas de comunicación científica, dirigidas a profesionistas, técnicos, estudiantes y profesores. Asimismo, se registran los diversos tipos de documentos que aparecen publicados, tales como son artículos, biografías, conferencias o discursos, correspondencia, cronologías, editorial, ensayos, entrevistas, estadísticas o encuestas, leyes o reglamentos, monografías, notas breves o noticias, proyectos técnicos o programas, reportes técnicos, reseñas de libro y revisiones bibliográficas. Con objeto de realizar un análisis bibliométrico especializado en artículos publicados en revistas con arbitraje por pares, %s ofrece la opción de realizar las distintas búsquedas disponibles aplicadas solamente al universo de revistas con arbitraje y considerando solamente los documentos clasificados como artículos y ensayos.','<a href="https://clase.dgb.unam.mx" target="_blank"><acronym title="$clase">CLASE</acronym></a>','<a href="https://periodica.dgb.unam.mx" target="_blank"><acronym title="$periodica">PERIÓDICA</acronym></a>','<span class="biblat"><acronym title="$biblat">Biblat</acronym></span>')}</p>

    <p>{_('Consultar lista de revistas arbitradas.')}</p>