<p><span class="biblat"><acronym title="{_('Bibliografía Latinoamericana')}">Biblat</acronym></span> {_('es un portal especializado en revistas científicas y académicas publicadas en América Latina y el Caribe, que ofrece los siguientes servicios:')}</p>
<ol>
  <li><p>{$clase=_('Citas Latinoamericanas en Ciencias Sociales y Humanidades') $periodica=_('Índice de Revistas Latinoamericanas en Ciencias') _sprintf('Referencias bibliográficas de los artículos y documentos publicados en más de 3,000 títulos indizados en %s y %s, mediante opciones de búsqueda básica y avanzada.', '<a href="https://clase.dgb.unam.mx" target="_blank"><acronym title="$clase">CLASE</acronym></a>','<a href="https://periodica.dgb.unam.mx" target="_blank"><acronym title="$periodica">PERIÓDICA</acronym></a>')}</p></li>

  <li><p>{$biblat=_('Bibliografía Latinoamericana') $unam=_('Universidad Nacional Autónoma de México') _sprintf('Acceso al texto completo de los artículos publicados en revistas de acceso abierto. %s ofrece dos tipos de acceso al texto completo: mediante enlaces hipertextuales a los sitios web de las revistas (recursos externos) y a través de la colección del acervo digital de la Hemeroteca Virtual Latinoamericana de la Dirección General de Bibliotecas y Servicios Digitales de Información %s, Universidad Nacional Autónoma de México %s.','<span class="biblat"><acronym title="$biblat">Biblat</acronym></span>','<a href="http://dgb.unam.mx" target="_blank">DGBSDI</a>','<a href="http://www.unam.mx" target="_blank"><acronym title="$unam">UNAM</acronym></a>')}</p></li>

  <li><p>{_sprintf('Frecuencias e %s extraídos de las revistas indizadas en %s y %s, en las colecciones %s así como de otras fuentes de información.','<a href="indicadores" target="_blank">indicadores bibliométricos</a>','<a href="https://clase.dgb.unam.mx" target="_blank"><acronym title="$clase">CLASE</acronym></a>','<a href="https://periodica.dgb.unam.mx" target="_blank"><acronym title="$periodica">PERIÓDICA</acronym></a>','<a href="http://www.scielo.org" target="_blank"><acronym title="Scientific Electronic Library Online">SciELO</acronym></a>')}</p></li>

  <li><p>{_sprintf('En %s se describen los Criterios de selección de revistas para su indización en %s y %s, que son la fuente de información principal de %s. Los editores de revistas pueden someter a evaluación su revista dirigiéndose a:','<a href="https://biblat.unam.mx/es/postular-revista/criterios-de-seleccion" target="_blank">Postular una revista</a>','<a href="https://clase.dgb.unam.mx" target="_blank"><acronym title="$clase">CLASE</acronym></a>','<a href="https://periodica.dgb.unam.mx" target="_blank"><acronym title="$periodica">PERIÓDICA</acronym></a>','<span class="biblat"><acronym title="Bibliografía Latinoamericana">Biblat</acronym></span>')} <a href="mailto:biblat@dgb.unam.mx">biblat@dgb.unam.mx</a>.</p></li>
																																										 
</ol>